# Generated by Django 4.1.4 on 2023-02-21 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialweb', '0003_posts_image_userprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comment',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='like',
            field=models.ManyToManyField(null=True, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
    ]
